tasks:
  - name: Setup Python Virtual Environment
    init: |
      python3.9 -m venv venv --system-site-packages
      source venv/bin/activate
      pip install -e .[all]
    command: source venv/bin/activate

vscode:
  extensions:
    - eamodio.gitlens
    - redhat.vscode-yaml
    - editorconfig.editorconfig
    - ms-python.python

image:
  file: .gitpod.Dockerfile