# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m venv venv --system-site-packages
          source venv/bin/activate
          pip install --upgrade pip
          pip install -e .[all]
      - name: Lint with flake8
        run: |
          source venv/bin/activate
          flake8 .
      - name: Test with Tox
        run: |
          source venv/bin/activate
          tox -- --coverage-report html
      - name: Build distribution package
        run: |
          source venv/bin/activate
          python setup.py bdist_wheel
      # - name: Publish distribution to PyPI
      #   if: startsWith(github.ref, 'refs/tags')
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     password: ${{ secrets.PYPI_TOKEN }}
